---
# gather service facts only at the beginning, when stopping services and only for small VPS
- name: Populate service facts
  service_facts:
  when:
  - ansible_memtotal_mb | int < 196
  - ansible_facts["services"] is not defined # true only on first run

- name: start/stop RAM-hungry services on low-mem machines
  become: true
  service: name="{{ item }}" state="{{ state | default("stopped") }}"
  when:
    - ansible_memtotal_mb | int < 196
    - item in services # true if item.service is installed
  with_items:
    - postgrey
    - postfix
    - grabrabbel # does not exist
  changed_when:
    - state == "started"
    - ansible_facts["services"][item]["state"] != "running"
